#set params based on environment

if [[ ${APP_STATE} = 'dev' ]]; then
  export IngestionParam="CAP_BUS_EFF_DT='${RUN_DATE}',CAP_RUN_ID='${RUN_ID}',CAP_APP_ID='${DCI_APP_ID}',REMEDY_ID=${REMEDY_ID},LOADTYPE=${LOADTYPE},EMH_INTEGRATE=${EMH_INTEGRATE},DROP_TABLE=${DROP_TABLE},CREATE_DYNAMIC=${CREATE_DYNAMIC},USE_IN_MEMORY=${USE_IN_MEMORY},TEMP_DATABASE=cap_dataproducts_temp,TARGET_DATABASE=cap_dataproducts,TARGET_TABLE_MAPRFS_PATH=${TARGET_TABLE_MAPRFS_PATH}"

elif [[ ${APP_STATE} = 'sit' ]]; then
  export IngestionParam="CAP_BUS_EFF_DT='${RUN_DATE}',CAP_RUN_ID='${RUN_ID}',CAP_APP_ID='${DCI_APP_ID}',REMEDY_ID=${REMEDY_ID},LOADTYPE=${LOADTYPE},EMH_INTEGRATE=${EMH_INTEGRATE},DROP_TABLE=${DROP_TABLE},CREATE_DYNAMIC=${CREATE_DYNAMIC},USE_IN_MEMORY=${USE_IN_MEMORY},TEMP_DATABASE=cap_dataproducts_temp,TARGET_DATABASE=cap_dataproducts,TARGET_TABLE_MAPRFS_PATH=${TARGET_TABLE_MAPRFS_PATH}"

elif [[ ${APP_STATE} = 'uat' ]]; then
  export IngestionParam="CAP_BUS_EFF_DT='${RUN_DATE}',CAP_RUN_ID='${RUN_ID}',CAP_APP_ID='${DCI_APP_ID}',REMEDY_ID=${REMEDY_ID},LOADTYPE=${LOADTYPE},EMH_INTEGRATE=${EMH_INTEGRATE},DROP_TABLE=${DROP_TABLE},CREATE_DYNAMIC=${CREATE_DYNAMIC},USE_IN_MEMORY=${USE_IN_MEMORY},TEMP_DATABASE=cap_dataproducts_temp,TARGET_DATABASE=cap_dataproducts,TARGET_TABLE_MAPRFS_PATH=${TARGET_TABLE_MAPRFS_PATH}"

else
  export IngestionParam="CAP_BUS_EFF_DT='${RUN_DATE}',CAP_RUN_ID='${RUN_ID}',CAP_APP_ID='${DCI_APP_ID}',REMEDY_ID=${REMEDY_ID},LOADTYPE=${LOADTYPE},EMH_INTEGRATE=${EMH_INTEGRATE},DROP_TABLE=${DROP_TABLE},CREATE_DYNAMIC=${CREATE_DYNAMIC},USE_IN_MEMORY=${USE_IN_MEMORY},TEMP_DATABASE=cap_dataproducts_temp,TARGET_DATABASE=cap_dataproducts,TARGET_TABLE_MAPRFS_PATH=${TARGET_TABLE_MAPRFS_PATH}"
fi
